import { escapeHtml, getSchoolDate, page, readForm, redirect, requireTeacher, sendHtml, validateUrl } from './_shared.js';
export default async function handler(request, response) {
  const auth = await requireTeacher(request, response); if (auth.redirect) return redirect(response, auth.redirect);
  const { supabase, profile } = auth; const queryDate = String(request.query?.date ?? getSchoolDate()); const selectedStudent = String(request.query?.student_id ?? ''); let message = '';
  if (request.method === 'POST') { const form = await readForm(request); const row = { student_id: String(form.get('student_id') ?? ''), assignment_date: String(form.get('assignment_date') ?? queryDate), title: String(form.get('title') ?? '').trim(), instructions: String(form.get('instructions') ?? '').trim() || null, url: String(form.get('url') ?? '').trim() }; if (!row.student_id || !row.title) message = 'Selecciona estudiante y escribe un título.'; else if (!validateUrl(row.url)) message = 'La URL de Kami debe ser válida.'; else { const { error } = await supabase.from('kami_assignments').insert(row); if (error) { console.error('Kami insert failed', error); message = 'No pudimos guardar la asignación.'; } else return redirect(response, `/teacher/kami?student_id=${row.student_id}&date=${row.assignment_date}`); } }
  const [{ data: students }, { data: assignments, error }] = await Promise.all([supabase.from('students').select('id, display_name').eq('active', true).order('display_name'), supabase.from('kami_assignments').select('id, title, instructions, url, students(display_name)').eq('assignment_date', queryDate).order('created_at')]); if (error) console.error('Kami list failed', error);
  const options = (students ?? []).map((s) => `<option value="${s.id}" ${s.id === selectedStudent ? 'selected' : ''}>${escapeHtml(s.display_name)}</option>`).join('');
  const items = (assignments ?? []).map((a) => `<li><strong>${escapeHtml(a.title)}</strong> — ${escapeHtml(a.students?.display_name ?? '')}<br><a href="${escapeHtml(a.url)}" target="_blank" rel="noopener noreferrer">Abrir Kami</a>${a.instructions ? `<p>${escapeHtml(a.instructions)}</p>` : ''}</li>`).join('');
  const body = `${message ? `<p class="teacher-error">${escapeHtml(message)}</p>` : ''}<section class="teacher-panel"><form class="teacher-form" method="post"><label>Estudiante<select name="student_id" required>${options}</select></label><label>Fecha<input name="assignment_date" type="date" value="${escapeHtml(queryDate)}" required></label><label>Título<input name="title" required></label><label>Instrucciones<textarea name="instructions"></textarea></label><label>URL de Kami<input name="url" type="url" required></label><button class="teacher-button" type="submit">Guardar asignación</button></form></section><section class="teacher-panel"><h2>Asignaciones de ${escapeHtml(queryDate)}</h2>${items ? `<ul>${items}</ul>` : '<p>No hay asignaciones para esta fecha.</p>'}</section>`;
  sendHtml(response, page('Clases Diversas', profile, body));
}
