import { escapeHtml, getSchoolDate, page, redirect, requireTeacher, sendHtml } from './_shared.js';
const zoneLabels = { lectura: 'Lectura', mecanografia: 'Mecanografía', matematicas: 'Matemáticas', clases_diversas: 'Clases Diversas', ingles: 'Inglés', ejercicio: 'Ejercicio' };
function minutes(seconds) { return `${Math.floor(Number(seconds ?? 0) / 60)} min`; }
export default async function handler(request, response) {
  const auth = await requireTeacher(request, response); if (auth.redirect) return redirect(response, auth.redirect);
  const { supabase, profile } = auth; const workDate = getSchoolDate(); const filter = String(request.query?.student ?? 'active');
  let studentQuery = supabase.from('students').select('id, display_name, active').order('display_name'); if (filter === 'active') studentQuery = studentQuery.eq('active', true); else if (filter !== 'all') studentQuery = studentQuery.eq('id', filter);
  const [{ data: students }, { data: progress, error }] = await Promise.all([studentQuery, supabase.from('zone_progress').select('student_id, zone, recorded_seconds, status, teacher_confirmed').eq('work_date', workDate)]); if (error) console.error('Progress query failed', error);
  const byStudent = new Map(); for (const row of progress ?? []) { const list = byStudent.get(row.student_id) ?? []; list.push(row); byStudent.set(row.student_id, list); }
  const options = [`<option value="active" ${filter === 'active' ? 'selected' : ''}>Estudiantes activos</option>`, `<option value="all" ${filter === 'all' ? 'selected' : ''}>Todos</option>`, ...(students ?? []).map((s) => `<option value="${s.id}" ${filter === s.id ? 'selected' : ''}>${escapeHtml(s.display_name)}</option>`)].join('');
  const rows = (students ?? []).map((s) => { const list = byStudent.get(s.id) ?? []; const active = list.find((p) => p.status === 'in_progress'); const time = list.map((p) => `${zoneLabels[p.zone] ?? p.zone}: ${minutes(p.recorded_seconds)}`).join('<br>') || 'Sin tiempo registrado'; return `<tr><td>${escapeHtml(s.display_name)}</td><td>${active ? escapeHtml(zoneLabels[active.zone] ?? active.zone) : 'Ninguna'}</td><td>${time}</td><td>${list.filter((p) => p.status === 'finished').length}</td><td>${list.some((p) => p.zone === 'ejercicio' && p.status === 'finished') ? 'Ejercicio marcado' : 'Pendiente'}</td><td>${list.some((p) => p.teacher_confirmed) ? 'Confirmado' : 'Sin confirmar'}</td></tr>`; }).join('');
  const body = `<section class="teacher-panel"><p>Fecha escolar: ${workDate}. El tiempo mostrado es <strong>tiempo de trabajo registrado</strong>, no prueba de finalización académica.</p><form><label>Filtro<select name="student" onchange="this.form.submit()">${options}</select></label></form>${rows ? `<table class="teacher-table"><thead><tr><th>Estudiante</th><th>Zona activa</th><th>Tiempo de trabajo registrado</th><th>Zonas terminadas</th><th>Ejercicio</th><th>Confirmación</th></tr></thead><tbody>${rows}</tbody></table>` : '<p>No hay estudiantes para mostrar.</p>'}</section>`;
  sendHtml(response, page('Progreso de hoy', profile, body));
}
